let RaceStarter = false
let textSprite: TextSprite = null
let Lama2 = sprites.create(img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..........11111...............
    ..........11111...............
    ..........11ddd...............
    ..........11dfdd..............
    ..........11dddd..............
    ...........1111...............
    ...........1111...............
    ...........1111...............
    ...........1111...............
    .111.......1111...............
    11111111..11111...............
    1111111111111111..............
    .111111111111111..............
    .111111111111111..............
    .111111111111111..............
    .11111111111111...............
    ..11d111111111d...............
    ..11dd....11.dd...............
    ..11dd....11.dd...............
    ...1.d.....1..d...............
    ...1.d.....1..d...............
    `, SpriteKind.Player)
let Lama1 = sprites.create(img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..........eeeee...............
    ..........eeeee...............
    ..........eeddd...............
    ..........eedfdd..............
    ..........eedddd..............
    ...........eeee...............
    ...........eeee...............
    ...........eeee...............
    ...........eeee...............
    .eee.......eeee...............
    eeeeeeee..eeeee...............
    eeeeeeeeeeeeeeee..............
    .eeeeeeeeeeeeeee..............
    .eeeeeeeeeeeeeee..............
    .eeeeeeeeeeeeeee..............
    .eeeeeeeeeeeeee...............
    ..eedeeeeeeeeed...............
    ..eedd....ee.dd...............
    ..eedd....ee.dd...............
    ...e.d.....e..d...............
    ...e.d.....e..d...............
    `, SpriteKind.Player)
let Traffic_Light = sprites.create(assets.image`Traffic Light`, SpriteKind.Player)
Lama1.y = 98
scene.setBackgroundColor(9)
tiles.setTilemap(tilemap`level1`)
timer.background(function () {
    pause(1000)
    Traffic_Light.image.replace(12, 2)
    pause(1000)
    Traffic_Light.image.replace(2, 12)
    Traffic_Light.image.replace(14, 5)
    pause(1000)
    Traffic_Light.image.replace(5, 14)
    Traffic_Light.image.replace(6, 7)
    pause(1000)
    Traffic_Light.destroy()
    textSprite = textsprite.create("Go!")
    textSprite.setMaxFontHeight(64)
    textSprite.setOutline(1, 15)
    textSprite.setPosition(90, 53)
    pause(1000)
    textSprite.destroy()
    RaceStarter = true
})
